#' @title
#' Generate package ASCII logo
#'
#' @description
#' This function is meant for generating or updating the logo. After running
#' this procedure we end up with what is stored in the [`parabar::LOGO`]
#' constant.
#'
#' @param template A character string representing the path to the logo
#' template.
#'
#' @param version A numerical vector of three positive integers representing the
#' version of the package to append to the logo.
#'
#' @return The ASCII logo.
#'
#' @examples \dontrun{
#' # Generate the logo.
#' logo <- make_logo()
#'
#' # Print the logo.
#' cat(logo, sep = "\n")}
#'
#' @keywords internal
make_logo <- function(template = "./inst/assets/logo/logo.txt", version = c(1, 0, 0)) {
    # Load the ASCII logo.
    logo <- readLines(template)

    # Redirect console output.
    sink("/dev/null")

    # Parse the logo.
    logo <- dput(logo)

    # Remove output redirection.
    sink()

    # Update versioning.
    logo <- gsub("{{major}}", version[1], logo, perl = TRUE)
    logo <- gsub("{{minor}}", version[2], logo, perl = TRUE)
    logo <- gsub("{{patch}}", version[3], logo, perl = TRUE)

    # Condensed version.
    logo <- paste(logo, collapse = "\n")

    return(logo)
}


#' @title
#' The package ASCII logo
#'
#' @description
#' The logo is generated by [parabar::make_logo()] and displayed on package
#' attach for interactive `R` sessions.
#'
#' @keywords internal
LOGO = ". . . . . . . . . . . . . . . . . . . . . . . . . . .\n.                              _             v1.0.0 .\n.                             | |                   .\n.   _ __    __ _  _ __   __ _ | |__    __ _  _ __   .\n.  | '_ \\  / _` || '__| / _` || '_ \\  / _` || '__|  .\n.  | |_) || (_| || |   | (_| || |_) || (_| || |     .\n.  | .__/  \\____||_|    \\____||____/  \\____||_|     .\n.  | |                                              .\n.  |_|                                              .\n.                                                   .\n. . . . . . . . . . . . . . . . . . . . . . . . . . .\n.                         .                         .\n.        https://parabar.mihaiconstantin.com        .\n.                         .                         .\n. . . . . . . . . . . . . . . . . . . . . . . . . . ."
