# `pkgdown` workflow.
name: pkgdown

# Set workflow permissions.
permissions: read-all

# Events.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]
  # Trigger manually via the GitHub UI.
  workflow_dispatch:

# Jobs to run.
jobs:

  # `pkgdown` job.
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    # Actions.
    steps:
      # Checkout.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup `pandoc`.
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Setup `R`.
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Setup package dependencies and extras.
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      # Build the site.
      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      # Deploy to GitHub pages.
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
