# Workflow name.
name: test-coverage

# Events.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Trigger manually via the GitHub UI.
  workflow_dispatch:

# Jobs.
jobs:

  # Test coverage job.
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    # Actions.
    steps:
      # Checkout.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup `R`.
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install `parabar` dependencies and `covr` package.
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      # Run the test coverage excluding specific lines.
      - name: Test coverage
        env:
          PROCESSX_NOTIFY_OLD_SIGCHLD: true
        run: covr::codecov(line_exclusions = list("R/parabar-package.R", "R/UserApiConsumer.R" = c(59:77)))
        shell: Rscript {0}
