# Workflow name.
name: test-coverage

# Set workflow permissions.
permissions: read-all

# Events.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Trigger manually via the GitHub UI.
  workflow_dispatch:

# Jobs.
jobs:

  # Test coverage job.
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Actions.
    steps:
      # Checkout.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup `R`.
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install package dependencies and `covr` package.
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      # Run the test coverage excluding specific lines.
      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package"),
            line_exclusions = list("R/parabar-package.R", "R/UserApiConsumer.R" = c(118:136))
          )
          covr::to_cobertura(cov)
        shell: Rscript {0}

      # Upload the coverage report to `Codecov``.
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
          file: ./cobertura.xml
          plugin: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      # Show the output of `testthat`.
      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      # Upload results on failure.
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
